stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - cd /var/docker-containers/StoryMe/dev/editor-dev
    - docker-compose -f docker-compose-dev.yml down
    - docker-compose -f docker-compose-dev.yml up -d --build
  only:
    - development
