version: '3.8'

services:
  storyme-editor:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile
    ports:
      - "8081:80" # Map port 80 of the container to port 8081 on the host
    restart: always
    volumes:
      - .:/app  # Mount the project directory to the /app directory in the container
      # Uncomment the line below and replace with the path to your custom Nginx configuration, if you have one
      # - ./path/to/your/nginx.conf:/etc/nginx/nginx.conf
    # Uncomment and replace with your actual environment variables, if needed
    # environment:
    #   - ENV_VAR_NAME=value
